#############################
#       Automations         #
#############################

################################################################################
# This section contains automations for the Harmony hub and controlling        #
# the entertainment system                                                     #
################################################################################

# Turn off the entertainment system via the Harmony hub
- id: pwr_off_tv_hub
  alias: "Power off the Television (HUB)"
  trigger:
    - platform: state
      entity_id: remote.living_room_tv
  condition:
    - condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity == "PowerOff" }}'
  action:
    - service: input_select.select_option
      entity_id: input_select.living_room_tv
      data:
        option: 'PowerOff'

# Turn on the entertainment system via the Harmony hub
- id: watch_fire_tv_surr_hub
  alias: "Watch Fire TV with Surround Sound (HUB)"
  trigger:
    - platform: state
      entity_id: remote.living_room_tv
  condition:
    - condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity == "FIRE TV WITH SURROUND" }}'
  action:
    - service: input_select.select_option
      entity_id: input_select.living_room_tv
      data:
        option: 'FIRE TV WITH SURROUND'

# Turn on the entertainment system via the Harmony hub
- id: watch_fire_tv_hub
  alias: "Watch Fire TV (HUB)"
  trigger:
    - platform: state
      entity_id: remote.living_room_tv
  condition:
    - condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity == "WATCH FIRE TV" }}'
  action:
    - service: input_select.select_option
      entity_id: input_select.living_room_tv
      data:
        option: 'WATCH FIRE TV'

# Turn on the entertainment system via the Harmony hub
- id: watch_bcast_tv_hub
  alias: "Watch Broadcast TV (HUB)"
  trigger:
    - platform: state
      entity_id: remote.living_room_tv
  condition:
    - condition: template
      value_template: '{{ trigger.to_state.attributes.current_activity == "WATCH TV" }}'
  action:
    - service: input_select.select_option
      entity_id: input_select.living_room_tv
      data:
        option: 'WATCH TV'

# Turn off the entertainment system via Homeassistant
- id: pwr_off_tv_ha
  alias: "Power off the Television (HA)"
  trigger:
    - platform: state
      entity_id: input_select.living_room_tv
      to: 'PowerOff'
  action:
    - service: script.turn_off
      entity_id: script.tvoff

# Turn on the entertainment system via Homeassistant
- id: watch_fire_tv_surr_ha
  alias: "Watch Fire TV with Surround Sound (HA)"
  trigger:
    - platform: state
      entity_id: input_select.living_room_tv
      to: 'FIRE TV WITH SURROUND'
  action:
    - service: script.turn_on
      entity_id: script.firetvsurround

# Turn on the entertainment system via Homeassistant
- id: watch_fire_tv_ha
  alias: "Watch Fire TV (HA)"
  trigger:
    - platform: state
      entity_id: input_select.living_room_tv
      to: 'WATCH FIRE TV'
  action:
    - service: script.turn_on
      entity_id: script.firetv

# Turn on the entertainment system via Homeassistant
- id: watch_bcast_tv_ha
  alias: "Watch Broadcast TV (HA)"
  trigger:
    - platform: state
      entity_id: input_select.living_room_tv
      to: 'WATCH TV'
  action:
    - service: script.turn_on
      entity_id: script.broadcasttv

################################################################################
# This section contains automations for controlling my desk lamp               #
################################################################################

# Turn on the desk lamp when movement is detected
- id: turn_on_desk_light_with_movement
  alias: Turn on desk light when there is movement
  trigger:
    - platform: state
      entity_id: sensor.movement
      to: '1'
  action:
    - service: homeassistant.turn_on
      entity_id: light.hue_white_lamp_7

# Turn off the desk lamp when there's no movement
- id: turn_off_desk_light_no_movement
  alias: Turn off desk light 10 minutes after last movement
  trigger:
    - platform: state
      entity_id: sensor.movement
      to: '0'
      for:
        minutes: 10
  action:
    - service: homeassistant.turn_off
      entity_id: light.hue_white_lamp_7

################################################################################
# This section contains automations for controlling the porch lights based     #
# on the Sun component. On at night, off in the morning.                       #
################################################################################

# Turn on the front door light at night
- id: front_door_night_light_on
  alias: Turn on front door light at night
  trigger:
    platform: sun
    event: sunset
    offset: '-00:45:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.front_door

# Turn off the front door light in the morning
- id: front_door_night_light_off
  alias: Turn off front door light in the morning
  trigger:
    platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_off
    entity_id: light.front_door

# Turn on the back door light at night
- id: back_door_night_light_on
  alias: Turn on back door light at night
  trigger:
    platform: sun
    event: sunset
    offset: '-00:45:00'
  action:
    service: homeassistant.turn_on
    entity_id: light.back_door

# turn off the back door light in the morning
- id: back_door_night_light_off
  alias: Turn off back door light in the morning
  trigger:
    platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_off
    entity_id: light.back_door

################################################################################
# This section contains automations for controlling kitchen and living room    #
# lights based on movement detection.                                          #
################################################################################

# Turn on the kitchen and living room lights when movement is detected
- id: Movement_in_room_lights_on
  alias: Turn on light when movement detected
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_motion_detector_sensor
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id:
      - switch.wemo_insight
      - light.living_room_fan_lights

# Turn off the kitchen and living room lights when movement is not detected for 30 min
- id: Movement_in_room_lights_off
  alias: Turn off light when no movement
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_motion_detector_sensor
    to: 'off'
    for:
      minutes: 10
  action:
    service: homeassistant.turn_off
    entity_id:
      - switch.wemo_insight
      - light.living_room_fan_lights

################################################################################
# Automations for reporting status of garage door sensors over MQTT            #
################################################################################

- id: right_garage_door_sensor_report
  alias: Report status of right garage door
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_garage_door_tilt_sensor_sensor
  action:
    service: mqtt.publish
    data:
      topic: "home/right_door/status"
      payload_template: '{{ states ("binary_sensor.ecolink_garage_door_tilt_sensor_sensor") }}'

- id: left_garage_door_sensor_report
  alias: Report status of left garage door
  trigger:
    platform: state
    entity_id: binary_sensor.ecolink_garage_door_tilt_sensor_sensor_2
  action:
    service: mqtt.publish
    data:
      topic: "home/left_door/status"
      payload_template: '{{ states ("binary_sensor.ecolink_garage_door_tilt_sensor_sensor_2") }}'

################################################################################
# Automations for reporting status of lights over MQTT                         #
################################################################################

- id: wemo_switch_mqtt_status_off
  alias: Wemo switch mqtt status off
  trigger:
    platform: state
    to: 'off'
    entity_id: switch.wemo_insight
  action:
    service: mqtt.publish
    data:
      topic: "home/kitchen/wemo/status"
#      payload_template: '{{ states ("switch.wemo_insight") }}'
      payload: 'off'

- id: wemo_switch_mqtt_status_on
  alias: Wemo switch mqtt status on
  trigger:
    platform: state
    to: 'on'
    entity_id: switch.wemo_insight
  action:
    service: mqtt.publish
    data:
      topic: "home/kitchen/wemo/status"
#      payload_template: '{{ states ("switch.wemo_insight") }}'
      payload: 'on'

- id: wemo_switch_mqtt_control
  alias: Wemo switch mqtt control
  trigger:
    platform: mqtt
    topic: "home/kitchen/wemo/set"
  action:
    service_template: 'homeassistant.turn_{{ trigger.payload }}'
    entity_id: switch.wemo_insight

- id: computer_desk_lamp_mqtt_status
  alias: Computer desk lamp mqtt status
  trigger:
    platform: state
    entity_id: light.hue_white_lamp_7
  action:
    service: mqtt.publish
    data:
      topic: "home/desk/status"
      payload_template: '{{ states ("light.hue_white_lamp_7") }}'

- id: computer_desk_lamp_mqtt_control
  alias: Computer desk lamp mqtt control
  trigger:
    platform: mqtt
    topic: "home/desk/set"
  action:
    service_template: 'homeassistant.turn_{{ trigger.payload }}'
    entity_id: light.hue_white_lamp_7

- id: computer_desk_lamp_mqtt_brightness_status
  alias: Computer desk lamp mqtt brightness status
  trigger:
    platform: state
    entity_id: light.hue_white_lamp_7
  action:
    service: mqtt.publish
    data:
      topic: "home/desk/bright/status"
      payload_template: '{{ states.light.hue_white_lamp_7.attributes.brightness }}'

- id: computer_desk_lamp_mqtt_brightness_control
  alias: Computer desk lamp mqtt brightness control
  trigger:
    platform: mqtt
    topic: "home/desk/bright/set"
  action:
    service: light.turn_on
    entity_id: light.hue_white_lamp_7
    data_template:
      brightness: '{{ trigger.payload }}'
