- id: Test Automation
  alias: Home Assistant Update Light Notification
  description: Turn on the Node Light when a Home Assistant update is available
  trigger:
  - entity_id: binary_sensor.updater
    from: 'off'
    platform: state
    to: 'on'
  action:
  - data:
      payload: 'ON'
      topic: hass/lamp2/switch
    service: mqtt.publish
