homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elev
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Include customizations
  customize: !include customize.yaml

# Enable cloud services
cloud:
config:

# Enable the iOS app
ios:

# Enable Z-Wave
zwave:
  usb_path: /dev/ttyACM0
  debug: True

# Enable the configurator UI
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_ip

# Enables the frontend
frontend:
  themes:
    happy:
      primary-color: green
    sad:
      primary-color: blue
    night:
      primary-color: darkred

# Database controls
recorder:
# Uncomment next line to use PostgreSQL
  # db_url: postgres://@/homeassistant
  purge_interval: 2
  purge_keep_days: 7

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 5
  trusted_networks:
    - 127.0.0.1

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Enable the Hydrawise irrigation component
hydrawise:
  access_token: !secret hydrawise_token
  scan_interval: 20

device_tracker:
  - platform: locative

# Enable the Ring doorbell component
ring:
  username: !secret ring_username
  password: !secret ring_password

# Enable the Foscam camera component
#camera:
#  platform: foscam
#  ip: !secret camera_ip
#  username: !secret camera_username
#  password: !secret camera_password

# Enable the text to speech component
tts:
  platform: google

# Enable the MQTT server component
mqtt:
  broker: !secret mqtt_ip
  username: !secret mqtt_username
  password: !secret mqtt_password
  client_id: HA_Server_6b7359

# Enable the MQTT statestream component
### Warning, will cause a lot of MQTT traffic ###
# Used with Blynk server and iOS app
# mqtt_statestream:
#   base_topic: homeassistant

# Enable the hue bridge component
hue:
  bridges:
    - host: !secret hue_ip

# Enable the Ecobee thermostat component
ecobee:
  api_key: !secret ecobee_api_key

# Add Logitech Harmony Remote
remote:
  - platform: harmony
    name: "Living Room TV"
    host: !secret logitech_harmony_ip

# Enable the History graph component
history_graph:
  gr1:
    name: PWS History
    entities:
      - sensor.pws_temp_f
      - sensor.pws_pressure_in

# Enable the Octoprint component
octoprint:
  - host: !secret octoprint_host
    api_key: !secret octoprint_api
    name: 'Ender 3'
    number_of_tools: 1

sensor:
  - platform: hydrawise

#  - platform: wunderground
#    api_key: !secret wunderground_api_key
#    monitored_conditions:
#      - temp_f
#      - pressure_in
#      - dewpoint_f
#      - weather_1d
#      - weather_1n
#      - weather_2d
#      - weather_2n
#      - weather_3d
#      - weather_3n
#      - weather_4d
#      - weather_4n
#    pws_id: !secret pws

  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: swap_use_percent
      - type: last_boot
      - type: processor_use
      - type: load_1m
      - type: load_5m
      - type: load_15m

  - platform: speedtest
    minute:
      - 55
      - 10
      - 25
      - 40
    monitored_conditions:
      - ping
      - download
      - upload

  - platform: mqtt
    state_topic: 'office/sensor1'
    name: 'Temperature'
    unit_of_measurement: 'deg F'
    value_template: '{{ value_json.temperature }}'

  - platform: mqtt
    state_topic: 'office/sensor1'
    name: 'Humidity'
    unit_of_measurement: '% RH'
    value_template: '{{ value_json.humidity }}'

  - platform: mqtt
    state_topic: 'office/sensor1'
    name: 'Movement'
    unit_of_measurement: 'bool'
    value_template: '{{ value_json.pir }}'

  - platform: ring
    monitored_conditions:
      - battery
      - last_activity
      - volume
      - last_ding
      - last_motion

  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - precip_type
      - precip_intensity
      - precip_probability
      - temperature
      - dew_point
      - wind_speed
      - wind_bearing
      - cloud_cover
      - humidity
      - pressure
      - temperature_max
      - temperature_min
      - uv_index
      - nearest_storm_distance
      - daily_summary

  - platform: template
# create sensor entities for the z-wave sensors
    sensors:
      garage_door_sensor_1:
        friendly_name: 'Left Garage Door'
        value_template: '{% if is_state("binary_sensor.ecolink_garage_door_tilt_sensor_sensor_2", "on") %}OPEN{% else %}CLOSED{% endif %}'
        icon_template: '{% if is_state("binary_sensor.ecolink_garage_door_tilt_sensor_sensor_2", "on") %}mdi:garage-open{% else %}mdi:garage{% endif %}'
      garage_door_sensor_2:
        friendly_name: 'Right Garage Door'
        value_template: '{% if is_state("binary_sensor.ecolink_garage_door_tilt_sensor_sensor", "on") %}OPEN{% else %}CLOSED{% endif %}'
        icon_template: '{% if is_state("binary_sensor.ecolink_garage_door_tilt_sensor_sensor", "on") %}mdi:garage-open{% else %}mdi:garage{% endif %}'
      pantry_door_sensor:
        friendly_name: 'Pantry Door'
        value_template: '{% if states.sensor.ge_32563_hinge_pin_smart_door_sensor_access_control_3.state == "23" %}closed{% elif states.sensor.ge_32563_hinge_pin_smart_door_sensor_access_control_3.state == "22" %}open{% endif %}'
        icon_template: '{% if states.sensor.ge_32563_hinge_pin_smart_door_sensor_access_control_3.state == "23" %}mdi:door{% elif states.sensor.ge_32563_hinge_pin_smart_door_sensor_access_control_3.state == "22" %}mdi:door-open{% endif %}'

# create sensor entities for the z-wave device's batteries
      pantry_door_sensor_battery:
        friendly_name: 'Pantry Door Sensor Battery'
        value_template: '{% if states.zwave.ge_32563_hinge_pin_smart_door_sensor_3 %} {{ states.zwave.ge_32563_hinge_pin_smart_door_sensor_3.attributes.battery_level }} {% else %} Unknown {% endif %}'
        unit_of_measurement: '%'
      garage_door_sensor_1_battery:
        friendly_name: 'Left Garage Door Sensor Battery'
        value_template: '{% if states.zwave.ecolink_garage_door_tilt_sensor_2 %} {{ states.zwave.ecolink_garage_door_tilt_sensor_2.attributes.battery_level }} {% else %} Unknown {% endif %}'
        unit_of_measurement: '%'
      garage_door_sensor_2_battery:
        friendly_name: 'Right Garage Door Sensor Battery'
        value_template: '{% if states.zwave.ecolink_garage_door_tilt_sensor %} {{ states.zwave.ecolink_garage_door_tilt_sensor.attributes.battery_level }} {% else %} Unknown {% endif %}'
        unit_of_measurement: '%'
      motion_sensor_battery:
        friendly_name: 'Motion Sensor Battery'
        value_template: '{% if states.zwave.ecolink_motion_detector %} {{ states.zwave.ecolink_motion_detector.attributes.battery_level }} {% else %} Unknown {% endif %}'
        unit_of_measurement: '%'

  - platform: pollen
    zip_code: !secret zip_code
    monitored_conditions:
      - allergy_average_forecasted
      - allergy_average_historical
      - allergy_index_today
      - allergy_index_tomorrow
      - allergy_index_yesterday
      - disease_average_forecasted

# Create my own custom allergy entities
  - platform: template
    sensors:
      allergy_today:
        friendly_name: "Today's allergy summary"
        value_template: "{{ states('sensor.allergy_index_today') }} - {{ state_attr('sensor.allergy_index_today', 'rating') }}"
      allergens_today:
        friendly_name: "Today's allergens"
        value_template: "{% if states('sensor.allergy_index_today.attributes.allergen_name_1') %}{{ state_attr('sensor.allergy_index_today', 'allergen_name_1') }}{% endif %}{% if states('sensor.allergy_index_today.attributes.allergen_name_2') %}, {{ state_attr('sensor.allergy_index_today', 'allergen_name_2') }}{% endif %}{% if states('sensor.allergy_index_today.attributes.allergen_name_3') %}{% else %}, {{ state_attr('sensor.allergy_index_today', 'allergen_name_3') }}{% endif %}"
      allergy_tomorrow:
        friendly_name: "Tomorrow's allergy summary"
        value_template: "{{ states('sensor.allergy_index_tomorrow') }} - {{ state_attr('sensor.allergy_index_tomorrow', 'rating') }}"
      allergens_tomorrow:
        friendly_name: "Tomorrow's allergens"
        value_template: "{% if states('sensor.allergy_index_tomorrow.attributes.allergen_name_1') %}{{ state_attr('sensor.allergy_index_tomorrow', 'allergen_name_1') }}{% endif %}{% if states('sensor.allergy_index_tomorrow.attributes.allergen_name_2') %}, {{ state_attr('sensor.allergy_index_tomorrow', 'allergen_name_2') }}{% endif %}{% if states('sensor.allergy_index_tomorrow.attributes.allergen_name_3') %}{% else %}, {{ state_attr('sensor.allergy_index_tomorrow', 'allergen_name_3') }}{% endif %}"
      allergy_summary:
        friendly_name: "Tomorrow's allergy summary"
        value_template: "{{ state_attr('sensor.allergy_index_forecasted_average_2', 'outlook') }}"
      flu_conditions:
        friendly_name: "Today's flu conditions"
        value_template: "{{ state_attr('sensor.cold__flu_forecasted_average_2', 'rating') }} - {{ state_attr('sensor.cold__flu_forecasted_average_2', 'trend') }}"

# adding Ring binary sensor. Not to be confused with Ring sensor.
binary_sensor:
  - platform: hydrawise
  - platform: ring
    monitored_conditions:
      - ding
      - motion

# Configuration for an MQTT Garage Door Controller (Cover)
switch:
  - platform: tplink
    host: 10.0.1.210
  - platform: hydrawise
  - platform: mqtt
    name: "Left Garage Door"
    state_topic: home/main_floor/garage/left_door/switch/status
    command_topic: home/main_floor/garage/left_door/switch/set
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 1
    icon: mdi:remote
  - platform: mqtt
    name: "Right Garage Door"
    state_topic: home/main_floor/garage/right_door/switch/status
    command_topic: home/main_floor/garage/right_door/switch/set
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 1
    icon: mdi:remote

light:
  - platform: mqtt
    name: "node light"
    state_topic: "hass/lamp2/status"
    command_topic: "hass/lamp2/switch"
    optimistic: false
  - platform: mqtt
    name: "Pantry Light"
    state_topic: "home/main_floor/pantry/stat/sonoff_switch/POWER"
    command_topic: "home/main_floor/pantry/cmnd/sonoff_switch/POWER"
    availability_topic: "home/main_floor/pantry/tele/sonoff_switch/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: mqtt
    name: "foyer lights"
    state_topic: "home/main_floor/foyer/stat/sonoff_switch/POWER"
    command_topic: "home/main_floor/foyer/cmnd/sonoff_switch/POWER"
    availability_topic: "home/main_floor/foyer/tele/sonoff_switch/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: mqtt
    name: "Front Room Light"
    state_topic: "home/main_floor/front_room1/stat/sonoff_switch/POWER"
    command_topic: "home/main_floor/front_room1/cmnd/sonoff_switch/POWER"
    availability_topic: "home/main_floor/front_room1/tele/sonoff_switch/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
  - platform: mqtt
    name: "Wine Rack lights"
    state_topic: "home/main_floor/wine_rack/stat/sonoff_switch/POWER"
    command_topic: "home/main_floor/wine_rack/cmnd/sonoff_switch/POWER"
    availability_topic: "home/main_floor/wine_rack/tele/sonoff_switch/LWT"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true

input_select:
  living_room_tv:
    name: "Living Room TV"
    options:
      - WATCH FIRE TV
      - PowerOff
      - WATCH TV
      - Watch a Movie
      - Use Mac
      - FIRE TV WITH SURROUND
    initial: PowerOff
    icon: mdi:monitor

script:
  tvoff:
    sequence:
      - service: remote.turn_off
        entity_id: remote.living_room_tv
        data:
          activity: -1
  firetvsurround:
    sequence:
      - service: remote.turn_on
        entity_id: remote.living_room_tv
        data:
          activity: 12106072
  firetv:
    sequence:
      - service: remote.turn_on
        entity_id: remote.living_room_tv
        data:
          activity: 12105863
  broadcasttv:
    sequence:
      - service: remote.turn_on
        entity_id: remote.living_room_tv
        data:
          activity: 12104283


#############################
#         Includes          #
#############################
automation: !include automations.yaml
zone: !include_dir_list zones/
group: !include groups.yaml
