homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret lat
  longitude: !secret lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elev
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Include customizations
  customize: !include customize.yaml

# Enable the iOS app
ios:

# Enable Z-Wave
zwave:
  usb_path: /dev/ttyACM0
  debug: True

# Enable the configurator UI
panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: !secret configurator_ip

# Enable config panel
config:

# Enables the frontend
frontend:
  themes:
    happy:
      primary-color: green
    sad:
      primary-color: blue
    night:
      primary-color: darkred

# Database controls
recorder:
  db_url: postgres://@/homeassistant
  purge_days: 8

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123
  ip_ban_enabled: True
  login_attempts_threshold: 5
  trusted_networks:
    - 127.0.0.1

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# password for Ring doorbell account
ring:
  username: !secret ring_username
  password: !secret ring_password

# Weather Prediction
sensor:
#  platform: yr
  - platform: wunderground
    api_key: !secret wunderground_api_key
    monitored_conditions:
      - temp_f
      - pressure_in
      - heat_index_f
      - dewpoint_f
      - weather_1d
      - weather_1n
      - weather_2d
      - weather_2n
      - weather_3d
      - weather_3n
      - weather_4d
      - weather_4n
    pws_id: !secret pws
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: last_boot
      - type: processor_use
  - platform: speedtest
    minute:
      - 55
      - 10
      - 25
      - 40
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: mqtt
    state_topic: 'office/sensor1'
    name: 'Temperature'
    unit_of_measurement: 'deg F'
    value_template: '{{ value_json.temperature }}'
  - platform: mqtt
    state_topic: 'office/sensor1'
    name: 'Humidity'
    unit_of_measurement: '% RH'
    value_template: '{{ value_json.humidity }}'
  - platform: mqtt
    state_topic: 'office/sensor1'
    name: 'Movement'
    unit_of_measurement: 'bool'
    value_template: '{{ value_json.pir }}'
  - platform: ring
    monitored_conditions:
      - battery
      - last_activity
      - volume
      - last_ding
      - last_motion
  - platform: darksky
    api_key: !secret darksky_api_key
    monitored_conditions:
      - summary
      - precip_probability
      - temperature
      - wind_speed
      - wind_bearing
      - humidity
      - pressure
      - temperature_max
      - temperature_min
      - nearest_storm_distance
  - platform: template
    sensors:
      garage_door_sensor_1:
        friendly_name: 'Left Garage Door'
        value_template: '{% if is_state("binary_sensor.ecolink_garage_door_tilt_sensor_sensor_2", "on") %}OPEN{% else %}CLOSED{% endif %}'
        icon_template: '{% if is_state("binary_sensor.ecolink_garage_door_tilt_sensor_sensor_2", "on") %}mdi:garage-open{% else %}mdi:garage{% endif %}'
  - platform: template
    sensors:
      garage_door_sensor_2:
        friendly_name: 'Right Garage Door'
        value_template: '{% if is_state("binary_sensor.ecolink_garage_door_tilt_sensor_sensor", "on") %}OPEN{% else %}CLOSED{% endif %}'
        icon_template: '{% if is_state("binary_sensor.ecolink_garage_door_tilt_sensor_sensor", "on") %}mdi:garage-open{% else %}mdi:garage{% endif %}'

# adding Ring binary sensor. Not to be confused with Ring sensor.
binary_sensor:
  - platform: ring
    monitored_conditions:
      - ding
      - motion

# foscam camera interface
#camera:
#  platform: foscam
#  ip: !secret camera_ip
#  username: !secret camera_username
#  password: !secret camera_password

# Text to speech
tts:
  platform: google

# Enable MQTT server
mqtt:
  client_id: HA_Server_6b7359

mqtt_statestream:
  base_topic: homeassistant

# Configuration for an MQTT Garage Door Controller (Cover)
switch:
  - platform: mqtt
    name: "Left Garage Door"
    state_topic: home/main_floor/garage/left_door/switch/status
    command_topic: home/main_floor/garage/left_door/switch/set
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 1
    icon: mdi:remote
  - platform: mqtt
    name: "Right Garage Door"
    state_topic: home/main_floor/garage/right_door/switch/status
    command_topic: home/main_floor/garage/right_door/switch/set
    payload_on: "1"
    payload_off: "0"
    optimistic: false
    qos: 1
    icon: mdi:remote

light:
  - platform: hue
    host: !secret hue_ip

  - platform: mqtt
    name: "node light"
    state_topic: "hass/lamp2/status"
    command_topic: "hass/lamp2/switch"
    optimistic: false

ecobee:
  api_key: !secret ecobee_api_key

# Add Logitech Harmony Remote
remote:
  - platform: harmony
    name: "Living Room TV"
    host: !secret logitech_harmony_ip

input_select:
  living_room_tv:
    name: "Living Room TV"
    options:
      - WATCH FIRE TV
      - PowerOff
      - WATCH TV
      - Watch a Movie
      - Use Mac
      - FIRE TV WITH SURROUND
    initial: PowerOff
    icon: mdi:monitor

script:
  tvoff:
    sequence:
      - service: remote.turn_off
        entity_id: remote.living_room_tv
        data:
          activity: -1
  firetvsurround:
    sequence:
      - service: remote.turn_on
        entity_id: remote.living_room_tv
        data:
          activity: 12106072
  firetv:
    sequence:
      - service: remote.turn_on
        entity_id: remote.living_room_tv
        data:
          activity: 12105863
  broadcasttv:
    sequence:
      - service: remote.turn_on
        entity_id: remote.living_room_tv
        data:
          activity: 12104283

#############################
#         Includes          #
#############################
automation: !include automations.yaml
zone: !include_dir_list zones/
group: !include groups.yaml
